### ISSUE TITLE
$add and $delete properties being added to Object.prototype

### ISSUE THREAD

**Issue by luislhl** [satismeter/satismeter-loader#1]
I was having a strange behavior in my app, and tracked it down as probably being caused by the Satismeter script we use, available at https://app.satismeter.com/satismeter.js

I don't know if there is a better place to post things like this, but since I didn't find one, I will put it up here.

The problem is that your script apparently is adding two properties, $add and $delete, to Object.prototype.
Can you confirm this is done by your script?

This causes a problem if someone tries to do something as simple as this after loading your script:
(Which is, in a simplified way, what another lib in my site was doing)

```
var a = {};
a.$delete = a.$delete || [];
a.$delete.push('a');
```

It seems very odd to me that you are changing the Object.prototype directly, since it affects every other Object that is created anywhere.
Is there any plan to change this behavior?

**Comment by jsedlacek** [comment]
Hi @luislhl,

Previous version of our survey framework used [Vue 0.11](https://011.vuejs.org/guide/list.html), which extends `Object` prototype with these methods. We have upgraded most users to a new version, which does not have this behavior. It seems you are still on the old version.

We will be migrating everybody away from the old version in following months, or I can migrate you now if you'd like. Just let me know.

Hope this helps!

**Comment by luislhl** [comment]
@jsedlacek , thanks for the answer, that's good to know.

It would be great if you could migrate me to the new version.
What data would I need to handle you to make it possible?

**Comment by jsedlacek** [comment]
@luislhl There is no need to change anything on your side. I can upgrade your SatisMeter project to the new version. Please write us on support@satismeter.com with project ID you'd like to upgrade (You'll find project ID in Integration settings / API).
